### ISSUE TITLE
[Crash][Window build exe] Crash when using Application.Quit

### ISSUE THREAD

**Issue by longvannguyendx** [keenanwoodall/Deform#19] opened 2019-10-03 10:14 UTC
Hi,
  If I use deforn plugin, when I quit the game by  Application.Quit. The game is crash.
  Could you please help me check this issue?
Thanks.

**Comment by keenanwoodall** [comment] 2019-10-03 15:06
I'm sorry to hear that, but I couldn't say what's causing this issue without more info. The best way for me to be able to help is if you can send me an example project that reproduces the bug. If you can't do that, I'll need you tell me more about the issue. What version of Unity are you using? What version of Deform? What is the nature of the crash? Is there an error popup or does the game freeze? Does it only crash when a Deformable is in the scene?

**Comment by keenanwoodall** [comment] 2019-10-15 18:36
Closing as there hasn't been a response and I can't reproduce it. If someone else runs into this and can give me more info feel free to reopen the issue.

**Closed as completed by keenanwoodall** 2019-10-15 18:36 UTC
